#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/eos/user/p/pcotte/311analysis/jobs/job.sh "charging_up_track_cuts_run.sh {1011} before_cuts June sum local 'true'"'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
