#! /bin/sh

$LSB_TRAPSIGS
$LSB_RCP1
$LSB_RCP2
$LSB_RCP3
# LSBATCH: User input
/usr/local/lsf/etc/job_starter '/eos/user/p/pcotte/311analysis/jobs/job.sh "track_cuts_run.sh {1172,1173,1174,1175,1176} common_purity June sum local true 'true'"'
ExitStat=$?
wait
# LSBATCH: End user input
true
exit `expr $? "|" $ExitStat`
